export const productsData = [
  {
    id: 1,
    name: "Gucci Leather Shoe",
    price: 20000,
    description: "Blue nice shoe from Gucci store direct to your house",
    availability: "Available",
    category: "Footwear",
    rating: 4.8,
    image: "/productsImg/gucci-shop.jpg",
  },
  {
    id: 2,
    name: "Louis Vuitton Handbag",
    price: 35000,
    description: "Elegant LV handbag made from premium leather material.",
    availability: "Out of stock",
    category: "Bags",
    rating: 4.7,
    image: "/productsImg/handbag.jpg",
  },
  {
    id: 3,
    name: "Nike Air Force 1",
    price: 18000,
    description: "Classic white sneakers with a comfortable sole and stylish look.",
    availability: "Available",
    category: "Footwear",
    rating: 4.9,
    image: "/productsImg/sneaker.jpg",
  },
  {
    id: 4,
    name: "Adidas Hoodie",
    price: 15000,
    description: "Warm and stylish hoodie perfect for casual outings.",
    availability: "Available",
    category: "Clothing",
    rating: 4.6,
    image: "/productsImg/hoodie.jpg",
  },
  {
    id: 5,
    name: "Rolex Submariner Watch",
    price: 150000,
    description: "Luxury timepiece crafted with stainless steel and sapphire glass.",
    availability: "Available",
    category: "Accessories",
    rating: 5.0,
    image: "/productsImg/rolex.jpg",
  },
];
